#page title
page_title                                : nunci

# App Info
ios_app_id                                : 1492839616                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.niftyapps.nunci                                          # Enter Google Play Store URL.                                      # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/icon.png                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : nunci uses artificial intelligence and advanced learning techniques to help language learners practice and improve their pronunciation, listening, reading, and writing skills.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Nifty Apps, LLC
your_link                                 : https://niftyapps.dev
your_city                                 :
email_address                             : nifty@niftyapps.dev
facebook_username                         :
instagram_username                        :
twitter_username                          :
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Practice your pronunciation
    description                           : Speak and nunci will correct your pronunciation
    fontawesome_icon_name                 : microphone

  - title                                 : Practice your listening
    description                           : Listen to nunci pronounce your words
    fontawesome_icon_name                 : volume-up

  - title                                 : Practice your reading and writing
    description                           : Type with nunci to help your reading, writing, and spelling
    fontawesome_icon_name                 : keyboard

  - title                                 : Improve your lexical diversity
    description                           : Let nunci help you create your own word bank
    fontawesome_icon_name                 : stream

  - title                                 : Automatically translate between languages
    description                           : Effortlessly translate your words and phrases to/from the language you are learning
    fontawesome_icon_name                 : language

  - title                                 : Easily switch between languages
    description                           : Switch between languages you are learning with ease
    fontawesome_icon_name                 : globe-asia



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#2892E8"
cover_overlay_transparency                : 1.0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#2892E8"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#ffffff"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#1d63ea"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#ffffff"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
